### PR TITLE
fix: Node level lazy parameter fix

### LINKED ISSUE #751: ros_gz_bridge: The global `lazy` parameter is not applied
## Environment
* OS Version: 22.04
* Source or binary build?: Source build of Humble branch

## Description
* Expected behavior: The parameter bridge and other nodes have a [`lazy` parameter](https://github.com/gazebosim/ros_gz/blob/ros2/ros_gz_bridge/src/parameter_bridge.cpp#L84). I would expect setting this parameter to `true` would serve as a default for all topics in my YAML file that don't explicitly define `lazy` themselves.
* Actual behavior: `lazy` parameter doesn't have any effect

## Steps to reproduce

1. Start a `parameter_bridge` with `lazy: True`
2. When the bridge starts it will still say (Lazy 0)

### PR DESCRIPTION
**Pull request by TannerGilbert**
# 🦟 Bug fix

Fixes #751

## Summary

Fix the lazy ROS parameter on the parameter_bridge and RosGzBridge nodes so it actually works as a global default for all bridge topics.   
   
What was broken:                                                                                                                           
- parameter_bridge.cpp declared and read the lazy parameter but never applied it to bridge configs — it was a dead variable              
- RosGzBridge (used for YAML config and parameter-based bridges) never declared a lazy parameter at all, so YAML-loaded bridges always defaulted to lazy: false                                                                                                              
                                                                                                                                           
What this PR does:
- Changes BridgeConfig::is_lazy from bool to std::optional<bool> so we can distinguish "not set" from "explicitly set to false"            
- The node-level lazy parameter now serves as the default for all bridges that don't explicitly set lazy per-entry in YAML                 
- Per-entry lazy: true or lazy: false in YAML overrides the node-level default                                                             
- Applies lazy to CLI-specified bridges in parameter_bridge as well

Behaviour:
 | Node-level `lazy` | Per-entry YAML `lazy` | Resolved value |
|---|---|---|
| `false` (default) | not set | `false` |
| `false` (default) | `true` | `true` |
| `false` (default) | `false` | `false` |
| `true` | not set | `true` |
| `true` | `true` | `true` |
| `true` | `false` | `false` |

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added a screen capture or video to the PR description that demonstrates the fix (as needed)
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] Updated Bazel files (if adding new files). Created an issue otherwise.
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers
- [ ] Was GenAI used to generate this PR? If so, make sure to add "Generated-by" to your commits. (See [this policy](https://osralliance.org/wp-content/uploads/2025/05/OSRF-Policy-on-the-Use-of-Generative-Tools-Generative-AI-in-Contributions.pdf) for more info.)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.

### CODE REVIEW

File: ros_gz_bridge/test/bridge_config.cpp
Comment (ahcorde) [inline ros_gz_bridge/test/bridge_config.cpp:364]:
```suggestion
}

// Verify that BridgeHandle::IsLazy() falls back to kDefaultLazy when
// BridgeConfig::is_lazy is std::nullopt, and returns the explicit value
// when it is set.
TEST(BridgeHandleIsLazy, NulloptFallsBackToDefault)
{
  ros_gz_bridge::BridgeConfig config;
  config.is_lazy = std::nullopt;
  // IsLazy() must return the hard-coded default when no value is set.
  EXPECT_EQ(ros_gz_bridge::kDefaultLazy, config.is_lazy.value_or(ros_gz_bridge::kDefaultLazy));
}

TEST(BridgeHandleIsLazy, ExplicitTrueIsRespected)
{
  ros_gz_bridge::BridgeConfig config;
  config.is_lazy = true;
  EXPECT_TRUE(config.is_lazy.value_or(ros_gz_bridge::kDefaultLazy));
}

TEST(BridgeHandleIsLazy, ExplicitFalseIsRespected)
{
  ros_gz_bridge::BridgeConfig config;
  config.is_lazy = false;
  EXPECT_FALSE(config.is_lazy.value_or(ros_gz_bridge::kDefaultLazy));
}
```

File: ros_gz_bridge/src/ros_gz_bridge.cpp
Comment (ahcorde) [inline ros_gz_bridge/src/ros_gz_bridge.cpp]:
```suggestion
void RosGzBridge::add_bridge(const BridgeConfig & input_config)
{

  // Resolve the laziness: if the caller left is_lazy as nullopt, inherit the
  // node-level "lazy" parameter so that the effective value is always explicit.
  BridgeConfig config = input_config;
  if (!config.is_lazy.has_value()) {
    bool node_lazy = kDefaultLazy;
    this->get_parameter("lazy", node_lazy);
    config.is_lazy = node_lazy;
  }
  bool gz_to_ros = false;
```

**Review by ahcorde — CHANGES_REQUESTED** [review]

**Comment by TannerGilbert** [comment]
Thanks for the review. Tried to add the suggestions. Will check if the pipeline runs now. If not I'll set up a Docker container for Jazzy as currently I was testing with Humble which needs some slight modifications.

File: ros_gz_bridge/test/bridge_config.cpp [hunk 1]
```diff
@@ -362,3 +362,26 @@ TEST_F(BridgeConfig, EmptyYAML)
...
+  ros_gz_bridge::BridgeConfig config;
+  config.is_lazy = true;
+  EXPECT_TRUE(config.is_lazy.value_or(ros_gz_bridge::kDefaultLazy));
+}
+TEST(BridgeHandleIsLazy, ExplicitFalseIsRespected)
+{
+  ros_gz_bridge::BridgeConfig config;
+  config.is_lazy = false;
+  EXPECT_FALSE(config.is_lazy.value_or(ros_gz_bridge::kDefaultLazy));
+}
```
Comment (ahcorde) [inline ros_gz_bridge/test/bridge_config.cpp]:
```suggestion
}

```

**Review by ahcorde — APPROVED** [review]
